name: Test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go (built-in cache)
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          check-latest: true
          cache: true

      - name: Test with unix
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        run: |
          sudo go env -w GOTOOLCHAIN=go1.25.0+auto
          sudo go test -v -covermode=count -coverprofile='coverage.out' ./...

      - name: Test with windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          go env -w GOTOOLCHAIN=go1.25.0+auto
          go test -v -covermode=count -coverprofile="coverage.out" ./...
